
services:
  db:
    image: mariadb:11.8.2
    container_name: movieapp-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: DB
      MARIADB_ALLOW_LOCAL_INFILE: 1
    ports:
      - "3308:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - movieapp-db-data:/var/lib/mysql
    networks:
      - movieapp-network

  adminer:
    image: adminer
    container_name: movieapp-adminer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - movieapp-network

  backend:
    build:
      context: https://github.com/messaoudRm/movieapp-api.git#branchB
      dockerfile: Dockerfile
    container_name: movieapp-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/DB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      TMDB_API_TOKEN: ${TMDB_API_TOKEN}
    depends_on:
      - db
    networks:
      - movieapp-network

  frontend:
    build:
      context: https://github.com/messaoudRm/movieapp-ui.git#main
      dockerfile: Dockerfile
      args:
        build_env: production
    container_name: movieapp-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - movieapp-network

  sentiment-analyzer:
    build:
      context: https://github.com/messaoudRm/sentiment-analyzer.git#main
      dockerfile: Dockerfile
    container_name: movieapp-sentiment-analyzer
    restart: always
    ports:
      - "8000:8000"
    networks:
      - movieapp-network

  minigame-api:
    build:
      context: https://github.com/messaoudRm/SuperPac.git#feature/superpac-container:superpac-api
      dockerfile: Dockerfile
    container_name: minigame-api
    restart: always
    ports:
      - "8081:8081"
    networks:
      - movieapp-network

volumes:
  movieapp-db-data:

networks:
  movieapp-network:
    driver: bridge
